image: node:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - .pnpm-store/

pages:
  script:
    - corepack enable
    - pnpm install --frozen-lockfile
    - pnpm docusaurus build --out-dir=public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
