# Allows Accesserator to create PR for updating API docs

issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:kartverket/accesserator:ref:refs/tags/v.*"

permissions:
  contents: write
  pull_requests: write
