# Permissions for argokit to create PRs in skip.kartverket.no

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:kartverket/argokit:ref:refs/heads/main

permissions:
  contents: write
  pull_requests: write
