# Allows Ztoperator to create PR for updating API docs

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:kartverket/ztoperator:ref:refs/heads/main

permissions:
  contents: write
  pull_requests: write
